### PR TITLE
added links to menu items

### PR DESCRIPTION
**Pull request by lauradumi**
added correct link paths to drop down menu items (sign in, log in and log out)

### CODE REVIEW

**Comment by lauradumi** [comment]
I've also styled the sign-up form

**Comment by lauradumi** [comment]
Screen Shot 2024-04-28 at 17 17 57

**Comment by KarimIssa1** [comment]
maybe change is host to "renter" and another checkbox for "tenant" to make it more user friendly?

**Comment by chrononaut76** [comment]
I reviewed the changes proposed in this PR and they LGTM.

**Review by chrononaut76 — APPROVED** [review]
LGTM

**Pull request merged**
